### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by LeChatP** [DvorakDwarf/disrust#4]
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/ebilloir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.49/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |

**Comment by DvorakDwarf** [comment]
From a cursory search this was an issue with nightly somewhere else. Are you running nightly ?

**Comment by jdiaz97** [comment]
Yeah you should mention your rustc version

I can compile perfectly in 1.83.0 but the app doesn't work haha
